esphome:
  name: esp32-daikin
  friendly_name: ESP32-Daikin

esp32:
  board: esp32-s3-devkitc-1
  variant: esp32s3
  flash_size: 16MB
  framework:
    type: esp-idf
    version: recommended


# Enable logging
logger:
  
# Enable Home Assistant API
api:
  encryption:
    key: "votre clé API"

ota:
  - platform: esphome
    password: "votre mot de passe"
safe_mode:
    reboot_timeout: 10min
    num_attempts: 5
    
mdns:
  disabled: false

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  power_save_mode: none
  output_power: 10

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Esp32-Daikin Fallback Hotspot"
    password: "votre mot de passe"

captive_portal:

web_server:
  port: 80
  version: 3

external_components:
  - source:
      type: git
      url: https://github.com/napster-08/Daikin-ekhhe
      ref: main
    components: [daikin_ekhhe]


button:
  - platform: restart
    name: "Daikin redemarrer"

uart:
  rx_pin: GPIO44
  tx_pin: GPIO43
  baud_rate: 9600
  parity: NONE
  stop_bits: 1
  id: my_uart
  debug:
    direction: TX

# Initialize the daikin UART receiver
daikin_ekhhe:
  - id: daikin_component
    update_interval: 10

sensor:
  - platform: daikin_ekhhe
    sonde_temp_eau_basse:
      name: "A: sonde température eau inferieur"
    sonde_temp_eau_haute:
      name: "B: sonde température eau superieur"
    sonde_température_de_degivrage:
      name: "C: sonde température degivrage"
    sonde_temp_air_souffle:
      name: "D: Sonde de température de l'apport d'air"
    sonde de temperature du gaz à l'entree de l'evaporateur:
      name: "E: Sonde de température du gaz d'entrée de l'évaporateur"
    sonde de temperature du gaz à la sortie de l'evaporateur:
      name: "F: Sonde de température du gaz de sortie de l'évaporateur"
    sonde de temperature du gaz de refoulement du compresseur:
      name: "G: Sonde température Gaz de refoulement compreseur"
    sonde de temperature pour capteur solaire:
      name: "H: Sonde de température du collecteur solaire"    
    ouverture_etape_EEV:
      name: "I: Etape d'ouverture de l'EEV"

binary_sensor:
  - platform: daikin_ekhhe
    dig1_config:
      name: "Entrée DIG1"
    dig2_config:
      name: "Entrée DIG2"
      filters:
      - invert:
    dig3_config:
      name: "Entrée DIG3"
      filters:
      - invert:



select:
  - platform: daikin_ekhhe
    etat_d'alimentation:
      name: "Etat d'alimentation"
    mode_fonctionnement:
      name: "Mode de fonctionnement"
    display_water_probe_temp:
      name: "P11: Valeur sonde d'eau afficher à l'ecran"
    off_peak_working_mode:
      name: "P24: Mode de fonctionnement en heure creuse"

number:
  - platform: daikin_ekhhe
    température de consigne anti-légionellose:
      name: "P3: Température de consigne de l'anti-légionelle"
    durée_antilégionelle:
      name: "P4: Durée de l'antilegionelle"
    température_mode_automatique:
      name: "Auto mode target temperature"
    température_mode_eco:
      name: "Eco mode target temperature"
    température_mode_boost:
      name: "Boost mode target temperature"
    température_mode_electric:
      name: "Electric mode target temperature"


text_sensor:
  - platform: daikin_ekhhe
    heure_actuelle:
      name: "Current Time UTC"

time:
  - platform: homeassistant
    id: homeassistant_time
    timezone: "Europe/Berlin"

